version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    restart: on-failure

  graylog:
    image: graylog/graylog:4.2
    environment:
      - GRAYLOG_PASSWORD_SECRET=admin12345678910
      - GRAYLOG_ROOT_PASSWORD_SHA2=48fb4f7bac17ca8d7e7f17b926365d117f0e319f00afa3c01a7b196a7f837a3f
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
    depends_on:
      - mongo
      - elasticsearch
    restart: on-failure

  mongo:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: on-failure

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "pedidos-criados-v1:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: on-failure

volumes:
  es_data:
  mongo_data:
